[Fe] Feature: Input components
starhuy1903/ads-management pull request #5
Opened 2023-12-12 13:11 UTC by ShinCoder

### Task

- https://graduation-project-internship.atlassian.net/browse/CI-30 

### Features

- Add 4 Input Components (ReactHookForm wrapper + MUI).
- Doc: https://graduation-project-internship.atlassian.net/wiki/x/AYBQAQ 
- Setup CDO Layout.
- Update getProfile logic.

### Screenshots

![image](https://github.com/starhuy1903/ads-management/assets/88935125/451d31c4-947f-4433-b44a-d5297070ed2e)

2023-12-13 01:59 UTC, starhuy1903 requested changes

2023-12-13 01:59 UTC, starhuy1903 commented on apps/management-app/src/components/Common/ControlledTextField.tsx
Change the style of showing the label

2023-12-13 10:44 UTC, ShinCoder commented on apps/management-app/src/components/Common/ControlledTextField.tsx
Changed

2023-12-14 09:29 UTC, starhuy1903 approved these changes

2023-12-14 09:29 UTC, merged